# Generated by Django 5.2.11 on 2026-04-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='category_ca_name_654722_idx'),
        ),
    ]
